spring:
  application:
    name: lovable-clone
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-clone
    username: postgres
    password: Vinay@2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt-secret-key: hkajhdkahdkhkshhskajdhkahdahshsakhhhhhhhhdsddhahkshj
